# Generated by Django 4.2.7 on 2023-12-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
