# Generated by Django 4.2.7 on 2023-11-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='validty_date_end',
            new_name='validity_date_end',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='validty_date_start',
            new_name='validity_date_start',
        ),
    ]
