# Generated by Django 4.2.7 on 2023-11-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_validty_date_end_project_validity_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='sem descricao', max_length=2000),
            preserve_default=False,
        ),
    ]
