# Generated by Django 4.2.7 on 2023-11-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('registration_period', models.DateField()),
                ('duration', models.CharField(max_length=80)),
                ('vacancies', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('offerer', models.CharField(max_length=200)),
                ('categories', models.ManyToManyField(to='graduations.category')),
            ],
        ),
    ]
