# Generated by Django 4.2.7 on 2023-11-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduation',
            name='registration_period',
        ),
        migrations.AddField(
            model_name='graduation',
            name='registration_date_end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='graduation',
            name='registration_date_start',
            field=models.DateField(default=None),
        ),
    ]
