# Generated by Django 4.2.7 on 2023-12-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduations', '0003_rename_titulo_graduation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduation',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
