# Generated by Django 4.2.7 on 2023-12-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpae', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpae',
            name='user',
        ),
        migrations.AddField(
            model_name='cpae',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cpae',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cpae',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='cpae',
            name='username',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cpae',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
